apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
    version: 1.21.0
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
    version: 1.21.0

