apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-blue
spec:
  selector:
    matchLabels:
      run: my-nginx
      version: 1.21.0
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
        version: 1.21.0
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.21.0
        ports:
        - containerPort: 80

